using System;

namespace SevenCrowns.Systems
{
    /// <summary>
    /// Tracks the player's weekly population pool ("people") available for recruitment.
    /// Resets at the start of each week to the total generated by owned farms.
    /// </summary>
    public interface IPopulationService
    {
        event Action<int> PopulationChanged;

        int GetAvailable();
        void Add(int delta);
        bool TrySpend(int amount);
        void ResetTo(int weeklyAmount);
    }
}

